---
version: "3.9"

services:
  mapnikbuilder:
    build:
      context: .
      dockerfile: Dockerfile.kx
      args:
        - ECR
    environment:
      - NPM_TOKEN
      - AWS_ACCESS_KEY_ID
      - AWS_SECRET_ACCESS_KEY
      - PATCH_VERSION_NUMBER
    volumes:
      - .:/src
