FROM 276514628126.dkr.ecr.ap-southeast-2.amazonaws.com/trixiebuild:master.latest

ENV DEBIAN_FRONTEND=noninteractive
RUN apt-get update -q
RUN apt-get install -qy --no-install-recommends \
    build-essential \
    gettext \
    git-core \
    make \
    ssh \
    python3-pip \
    nodejs \
    npm \
    libproj-dev \
    libgdal-dev \
    libgeotiff-dev \
    libmapnik-dev

RUN node --version

RUN echo '//registry.npmjs.org/:_authToken=${NPM_TOKEN}' > ~/.npmrc

ENV NPM_TOKEN=
ENV AWS_ACCESS_KEY_ID=
ENV AWS_SECRET_ACCESS_KEY=

ENV AWS_DEFAULT_REGION=ap-southeast-2
RUN pip install --break-system-packages awscli

VOLUME /src
WORKDIR /src
