_build_step_amd64: &_build_step_amd64
  command: "make && make publish-binary"
  plugins:
    docker-compose#v4.9.0:
      args:
        - NODE_VERSION
      run: mapnikbuilder
      config: docker-compose.yml
      env:
        - NPM_TOKEN
        - AWS_ACCESS_KEY_ID
        - AWS_SECRET_ACCESS_KEY
        - AWS_SESSION_TOKEN
        - "PATCH_VERSION_NUMBER=${BUILDKITE_BUILD_NUMBER}"
    cultureamp/aws-assume-role#v0.2.0:
      role: "arn:aws:iam::139273981395:role/s3-kx-publish-node-binaries"

steps:
  - group: "build binaries for amd64"
    key: "amd64"
    steps:
      - <<: *_build_step_amd64
        name: ":building_construction: Build amd64 binary (:nodejs: node=8)"
        env:
          NODE_VERSION: "8"
      - <<: *_build_step_amd64
        name: ":building_construction: Build amd64 binary (:nodejs: node=10)"
        env:
          NODE_VERSION: "10"

  - wait

  - name: "Publish npm package"
    command: "make publish-npm"
    plugins:
      docker-compose#v3.7.0:
        build: mapnikbuilder
        args:
          - "NODE_VERSION=8"
        run: mapnikbuilder
        config: docker-compose.yml
        env:
          - NPM_TOKEN
          - "PATCH_VERSION_NUMBER=${BUILDKITE_BUILD_NUMBER}"
